Add build-success CI flow step
This is prerequisite for requiring green on merge, and for using merge
queue.

(cherry picked from commit f0a0a323a83ac9b87bed8ee2696f0f43e84b1c53)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -204,6 +204,51 @@ jobs:
             -pl :galaxy-buffer-discovery-client,:galaxy-buffer-data-client,:galaxy-buffer-discovery-server,:galaxy-buffer-data-server,:schema-discovery-core \
             -Drevision=${{ needs.determine-version.outputs.version }}
 
+  build-success:
+    if: ${{ always() }} # if `failure()` would not work for cancellations, `!success()` would not work for skipped jobs
+    runs-on: [self-hosted, sep-cicd, gha-fleet-nano]
+    needs:
+      [
+        artifact-checks,
+        build-pt,
+        build-test-matrix,
+        check-commit,
+        check-commits-dispatcher,
+        deploy-maven,
+        determine-version,
+        docker-images,
+        error-prone-checks,
+        hive-tests,
+        maven-checks,
+        pt,
+        salesforce-tests,
+        test,
+        test-jdbc-compatibility,
+        test-other-modules,
+        web-ui-checks,
+      ]
+    steps:
+      - name: "Check results"
+        run: |
+          # generated by TestCiWorkflow
+          echo '${{ needs.artifact-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "artifact-checks" failed' >&2; exit 1; }
+          echo '${{ needs.build-pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-pt" failed' >&2; exit 1; }
+          echo '${{ needs.build-test-matrix.result }}' | grep -xE 'success|skipped' || { echo 'Job "build-test-matrix" failed' >&2; exit 1; }
+          echo '${{ needs.check-commit.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commit" failed' >&2; exit 1; }
+          echo '${{ needs.check-commits-dispatcher.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commits-dispatcher" failed' >&2; exit 1; }
+          echo '${{ needs.deploy-maven.result }}' | grep -xE 'success|skipped' || { echo 'Job "deploy-maven" failed' >&2; exit 1; }
+          echo '${{ needs.determine-version.result }}' | grep -xE 'success|skipped' || { echo 'Job "determine-version" failed' >&2; exit 1; }
+          echo '${{ needs.docker-images.result }}' | grep -xE 'success|skipped' || { echo 'Job "docker-images" failed' >&2; exit 1; }
+          echo '${{ needs.error-prone-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone-checks" failed' >&2; exit 1; }
+          echo '${{ needs.hive-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "hive-tests" failed' >&2; exit 1; }
+          echo '${{ needs.maven-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "maven-checks" failed' >&2; exit 1; }
+          echo '${{ needs.pt.result }}' | grep -xE 'success|skipped' || { echo 'Job "pt" failed' >&2; exit 1; }
+          echo '${{ needs.salesforce-tests.result }}' | grep -xE 'success|skipped' || { echo 'Job "salesforce-tests" failed' >&2; exit 1; }
+          echo '${{ needs.test.result }}' | grep -xE 'success|skipped' || { echo 'Job "test" failed' >&2; exit 1; }
+          echo '${{ needs.test-jdbc-compatibility.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-jdbc-compatibility" failed' >&2; exit 1; }
+          echo '${{ needs.test-other-modules.result }}' | grep -xE 'success|skipped' || { echo 'Job "test-other-modules" failed' >&2; exit 1; }
+          echo '${{ needs.web-ui-checks.result }}' | grep -xE 'success|skipped' || { echo 'Job "web-ui-checks" failed' >&2; exit 1; }
+
   maven-checks:
     runs-on: [self-hosted, sep-cicd, gha-fleet-small]
     strategy:
