[TEMPORARY] Add testing infrastructure for `trino-redshift`
The test infrastructure logic is copied from `starburst-enterprise`
and adapted to the needs of this project by using bash scripts for
provisioning testing infrastructure for the `trino-redshift` connector.

The state of the code will be revised once the corresponding PR
https://github.com/trinodb/trino/pull/15817
from Trino OSS will be merged.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -506,6 +506,7 @@ jobs:
             !:trino-postgresql,
             !:trino-raptor-legacy,
             !:trino-redis,
+            !:trino-redshift,
             !:trino-singlestore,
             !:trino-sqlserver,
             !:trino-test-jdbc-compatibility-old-server,
@@ -1106,3 +1107,67 @@ jobs:
           check_name: ${{ github.job }} with secrets
           conclusion: ${{ job.status }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
+
+  redshift:
+    name: test (plugin/trino-redshift)
+    runs-on: [ sep-cicd, gha-fleet-small ]
+    env:
+      AWS_REGION: us-east-2
+      AWS_ACCESS_KEY_ID: ${{ secrets.ENG_AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.ENG_AWS_SECRET_ACCESS_KEY }}
+      REDSHIFT_SUBNET_GROUP_NAME: redshift-cicd-subnet-group
+      REDSHIFT_NODE_TYPE: dc2.large
+      REDSHIFT_DATABASE_NAME: testdb
+      REDSHIFT_IAM_ROLES: arn:aws:iam::888469412714:role/redshift-cicd
+      REDSHIFT_VPC_SECURITY_GROUP_IDS: "[\"sg-0ad7ac36a73650b08\", \"sg-012799e2208deb2ab\"]"
+      REDSHIFT_S3_TPCH_TABLES_ROOT: "s3://starburstdata-engineering-redshift-test"
+      REDSHIFT_PUBLICLY_ACCESSIBLE: false
+    timeout-minutes: 60
+    steps:
+      - name: "GHA Node Info"
+        run: curl -SsL --retry 3 http://instance-data/latest/dynamic/instance-identity/document || true
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # checkout all commits to be able to determine merge base for GIB
+          ref: |
+            ${{ github.event_name == 'repository_dispatch' &&
+                github.event.client_payload.pull_request.head.sha == github.event.client_payload.slash_command.args.named.sha &&
+                format('refs/pull/{0}/head', github.event.client_payload.pull_request.number) || '' }}
+      - uses: ./.github/actions/setup
+      - name: Maven Install
+        run: |
+          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
+          $RETRY $MAVEN clean install ${MAVEN_FAST_INSTALL} ${MAVEN_GIB} -Dgib.logImpactedTo=gib-impacted.log -am -pl :trino-redshift
+          if [ ! -f gib-impacted.log ] || grep -q trino-redshift gib-impacted.log; then
+            echo "REDSHIFT_EXECUTE_TESTS=true" >> $GITHUB_ENV
+          fi
+      - name: Cloud Redshift Tests
+        if: env.REDSHIFT_EXECUTE_TESTS == 'true'
+        run: |
+          source bin/redshift/setup-aws-redshift.sh
+          bin/redshift/run-mvn-tests.sh
+      - name: Clean up ephemeral Redshift Cluster
+        # Cancelled workflows may have left the ephemeral cluster running
+        if: always()
+        run: bin/redshift/delete-aws-redshift.sh
+      - name: Upload test results
+        uses: actions/upload-artifact@v3
+        # Upload all test reports only on failure, because the artifacts are large
+        if: failure()
+        with:
+          name: result ${{ github.job }}
+          path: |
+            **/target/surefire-reports
+            **/target/checkstyle-*
+      - name: Upload test report
+        uses: actions/upload-artifact@v3
+        # Always upload the test report for the annotate.yml workflow,
+        # but only the single XML file to keep the artifact small
+        if: always()
+        with:
+          # Name prefix is checked in the `Annotate checks` workflow
+          name: test report ${{ github.job }}
+          if-no-files-found: ignore
+          path: |
+            **/surefire-reports/TEST-*.xml
+          retention-days: ${{ env.TEST_REPORT_RETENTION_DAYS }}
